---
title: "Revision 7"
output: html_document
---

### Revision

#### Question 1.

```{r}
# We create the points in R
x1 <- c(6, 5)
x2 <- c(4, 6)
x3 <- c(1, 1)
x4 <- c(5, 4)
x5 <- c(2, 1)
x6 <- c(3, 5)
x7 <- c(7, 4)
x8 <- c(1, 3)

X <- rbind(x1, x2, x3, x4, x5, x6, x7, x8) # a, b and c are combined per row
colnames(X) <- c("x", "y") # rename columns

X # display the points
```

```{r}
# The distance is found using the dist() function:
distance <- dist(X, method = "euclidean")
distance # display the distance matrix
```

```{r}
# Agglomerative Hierarchical Clustering for single linkage
start.time <- Sys.time()
ahc.s <- hclust(distance, method="single")
ahc.s
end.time <- Sys.time()
print(end.time - start.time)
```

```{r}
# Plotting a dendrogram for single linkage
plot(ahc.s, hang = -1, cex = 0.6, main="Single Linkage: Cluster Dendrogram")
```


#### Question 2.

```{r}
# We create the points in R
x1 <- c(6, 5, 4)
x2 <- c(0, 0, 0)
x3 <- c(1, 1, -2)
x4 <- c(7, 3, -1)
x5 <- c(2, -1, -1)
x6 <- c(4, 4, 4)

d <- rbind(x1, x2, x3, x4, x5, x6) # a, b and c are combined per row
colnames(d) <- c("x", "y", "z") # rename columns

d # display the points
```


```{r}
# The distance is found using the dist() function:
d.dist <- dist(d, method = "euclidean")
d.dist # display the distance matrix
```


```{r}
# Agglomerative Hierarchical Clustering for single linkage
start.time <- Sys.time()
ahc.c <- hclust(d.dist, method="complete")
ahc.c
end.time <- Sys.time()
print(end.time - start.time)
```


```{r}
# Plotting a dendrogram for single linkage
plot(ahc.c, hang = -1, cex = 0.6, main="Complete Linkage: Cluster Dendrogram")
```





